### ISSUE TITLE
Build-CI beépítése

### ISSUE THREAD

**Issue by aront22** [BME-MIT-IET/iet-hf-2022-mind1-a-nev#2]
Build keretrendszer beüzemelése, ha még nincs (Maven, Gradle...) + CI beüzemelése, ha még nincs (Actions, Travis, AppVeyor, Azure Pipelines...)

**Comment by aront22** [comment]
Létrehoztam egy build és test futattó workflow macOS-hez is

414151d717a259f5015546ef2eedf324d739d27f

**Comment by aront22** [comment]
Javítottam a build workflow nevét

eefc900f4d1e1eae62fac3ae912635043bfd89ef

**Comment by szabi43** [comment]
A BenchmarkDotNethez hozzá kéne adni a parancsot: dotnet run -p RDFSharp.Benchmark.csproj -c Release. Az RDFSharp.Benchmark mappából kell kiadni.

**Comment by aront22** [comment]
> A BenchmarkDotNethez hozzá kéne adni a parancsot: dotnet run -p RDFSharp.Benchmark.csproj -c Release. Az RDFSharp.Benchmark mappából kell kiadni.

Szerintem ez nem megvalósítható ilyen formában mivel nem lehet dotnet run parancsot használni egy ilyen workflowban.

**Comment by aront22** [comment]
Rövid dokumentáció írás a feladathoz
d7c19739153f4fe398e7eb050027181cf6c9dc87

master -> main átnevezések
a9907b6b1d2644561ad7b0b2b28c68522cf49b90
015960ab2252ffec719e09ebc66a2e7a0cdb81a5
0784c9800955acb28772a4211af46c44f226bf50
